- name: Configure infra server
  hosts: infra
  become: true
  roles:
    - name: nginx
    - name: geerlingguy.docker
      vars:
        docker_users: [infra]
    - name: whoami
      vars:
        whoami_domain: infra.musur.pl
